# Generated by Django 2.1.7 on 2019-03-20 08:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Права и обязанности',
                'verbose_name_plural': 'Права и обязанности',
            },
        ),
    ]
