# Generated by Django 2.1.7 on 2019-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Страница'),
            preserve_default=False,
        ),
    ]
