# Generated by Django 2.1.7 on 2019-03-20 09:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_laws_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisoryAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Страница')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контролирующие органы',
                'verbose_name_plural': 'Контролирующие органы',
            },
        ),
    ]
