# Generated by Django 2.1.7 on 2019-03-19 15:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='jobinfo',
            field=tinymce.models.HTMLField(verbose_name='О вакансии'),
        ),
    ]
