# Generated by Django 2.1.7 on 2019-03-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
    ]
