# Generated by Django 2.1.7 on 2019-05-26 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['discount'],
            },
        ),
        migrations.CreateModel(
            name='DoctorMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность врача',
                'verbose_name_plural': 'Специальности врачей',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Мед. учреждение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.UserProfile.get_picture_url, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='information',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oklad',
            field=models.PositiveIntegerField(default=0, verbose_name='Оклад'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ref_doc',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент специалиста'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='users.Discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_main',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.DoctorMain', verbose_name='Специальность'),
        ),
    ]
