# Generated by Django 2.1.7 on 2019-03-27 11:20

from django.db import migrations, models
import news.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Новость')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('image', models.ImageField(upload_to=news.models.Novost.get_picture_url, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
