# Generated by Django 2.1.7 on 2019-03-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novost',
            old_name='news',
            new_name='text',
        ),
    ]
