# Generated by Django 2.1.7 on 2019-03-29 10:19

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок слайда')),
                ('text', models.CharField(max_length=250, verbose_name='Текст слайда')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать слайд')),
                ('image', models.ImageField(upload_to=landing.models.Slider.get_picture_url, verbose_name='Фото слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
