# Generated by Django 2.1.7 on 2019-04-07 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicemain_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Врачи'),
        ),
    ]
