# Generated by Django 2.1.7 on 2019-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190407_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='peoples.Doctor', verbose_name='Врачи'),
        ),
    ]
