# Generated by Django 2.1.7 on 2019-04-19 15:11

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190407_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.ServiceMain.get_picture_url, verbose_name='Фото'),
        ),
    ]
