# Generated by Django 2.1.7 on 2019-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicemain_service_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemain',
            old_name='service_counter',
            new_name='counter',
        ),
        migrations.AddField(
            model_name='service',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
