# Generated by Django 2.1.7 on 2019-06-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='answer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
