# Generated by Django 2.1.7 on 2019-03-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0005_auto_20190305_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта'),
        ),
    ]
