# Generated by Django 2.1.7 on 2019-03-05 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peoples', '0006_people_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='people_ptr',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='people_ptr',
        ),
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
