# Generated by Django 2.1.7 on 2019-03-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0007_auto_20190305_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='discounts.Discount', verbose_name='Скидка'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
