# Generated by Django 2.1.7 on 2019-03-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0008_auto_20190305_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='clients', to='discounts.Discount', verbose_name='Скидка'),
        ),
    ]
