# Generated by Django 2.1.7 on 2019-03-19 10:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0011_director_mainoperator'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='information',
            field=tinymce.models.HTMLField(default=123, verbose_name='Информация'),
            preserve_default=False,
        ),
    ]
