# Generated by Django 2.1.7 on 2019-03-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0012_doctor_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный телефон')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('name', models.CharField(max_length=250, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctormain', to='peoples.DoctorMain', verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
