# Generated by Django 2.1.7 on 2019-03-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0014_auto_20190324_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='peoples.DoctorMain', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='mainoperator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainoperators', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
    ]
