# Generated by Django 2.1.7 on 2019-03-28 11:44

from django.db import migrations, models
import peoples.models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0015_auto_20190324_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=peoples.models.Doctor.get_picture_url, verbose_name='Фото'),
        ),
    ]
