# Generated by Django 2.1.7 on 2019-04-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0017_auto_20190330_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный телефон')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('agency', models.CharField(max_length=250, verbose_name='Мед. учреждение')),
            ],
            options={
                'verbose_name': 'Мед. учреждение',
                'verbose_name_plural': 'Мед. учреждения',
            },
        ),
    ]
