# Generated by Django 2.1.7 on 2019-04-07 06:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0018_outsidedoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный телефон')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронная почта')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Агенты',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.AlterModelOptions(
            name='outsidedoctor',
            options={'verbose_name': 'Внешние врачи', 'verbose_name_plural': 'Внешние врачи'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='information',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
