# Generated by Django 2.1.7 on 2019-06-02 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_order', to='services.Service', verbose_name='Анализ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_order', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Анализ в заказе',
                'verbose_name_plural': 'Анализы в заказе',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250, verbose_name='Заказчик')),
                ('client_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('client_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('client_dob', models.DateField(verbose_name='Дата рождения')),
                ('client_mail', models.EmailField(blank=True, max_length=250, null=True, verbose_name='E-mail')),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Итоговая цена')),
                ('status', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ServiceInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_order', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_order', to='orders.Order', verbose_name='Заказ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_order', to='services.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в заказе',
                'verbose_name_plural': 'Услуги в заказе',
            },
        ),
        migrations.AddField(
            model_name='analysisinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_order', to='orders.Order', verbose_name='Заказ'),
        ),
    ]
