# Generated by Django 2.1.7 on 2019-04-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisinorder',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_order', to='services.Service', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='analysisinorder',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_order', to='peoples.Doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='serviceinorder',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_order', to='peoples.Doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='serviceinorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_order', to='services.Service', verbose_name='Услуга'),
        ),
    ]
