# Generated by Django 2.1.7 on 2019-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190415_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisinorder',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceinorder',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
