# Generated by Django 2.1.7 on 2019-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190415_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinorder',
            name='city',
            field=models.CharField(default=2, max_length=250, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceinorder',
            name='city',
            field=models.CharField(default=2, max_length=250, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
