# Generated by Django 2.1.7 on 2019-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_client_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_mail',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
    ]
