# Generated by Django 2.1.7 on 2019-04-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190415_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clinet_address',
            new_name='client_address',
        ),
    ]
