# Generated by Django 2.1.7 on 2019-03-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приёма')),
                ('is_work', models.BooleanField(default=False, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Дата приёма',
                'verbose_name_plural': 'Даты приёма',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время приёма')),
                ('is_free', models.BooleanField(default=True, verbose_name='Свободно')),
            ],
            options={
                'verbose_name': 'Время приёма',
                'verbose_name_plural': 'Время приёма',
                'ordering': ['time'],
            },
        ),
    ]
