# Generated by Django 2.1.7 on 2019-05-26 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приёма')),
                ('is_work', models.BooleanField(default=False, verbose_name='Рабочий день')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdates', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('workcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdates', to='schedules.WorkCity', verbose_name='Город приёма')),
            ],
            options={
                'verbose_name': 'Дата приёма',
                'verbose_name_plural': 'Даты приёма',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время приёма')),
            ],
            options={
                'verbose_name': 'Время приёма',
                'verbose_name_plural': 'Время приёма',
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='workdate',
            name='worktimes',
            field=models.ManyToManyField(related_name='workdates', to='schedules.WorkTime', verbose_name='Рабочие часы'),
        ),
    ]
