# Generated by Django 2.1.7 on 2019-03-31 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0017_auto_20190330_1056'),
        ('schedules', '0002_workdate_worktimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdate',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workdates', to='peoples.Doctor', verbose_name='Врач'),
            preserve_default=False,
        ),
    ]
