# Generated by Django 2.1.7 on 2019-04-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_workcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdate',
            name='workcities',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='workdates', to='schedules.WorkCity', verbose_name='Город приёма'),
            preserve_default=False,
        ),
    ]
