# Generated by Django 2.1.7 on 2019-04-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_workdate_workcities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdate',
            old_name='workcities',
            new_name='workcity',
        ),
    ]
