# Generated by Django 2.1.7 on 2019-04-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_remove_worktime_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcity',
            name='address',
            field=models.CharField(default=123, max_length=250, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workcity',
            name='phone',
            field=models.CharField(default=123, max_length=250, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
